version: '2.1'

services:
  python:
    image: compose/python_app
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis_4.0.2
    ports:
      - 6379:6379